set nocompatible
set autoread
set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set autoindent
set backspace=eol,start,indent
set ruler
set cmdheight=2
set confirm
set visualbell
set noerrorbells
set t_vb=
set mouse=a
set number
set tabstop=4
set ai
set si
set expandtab
set shiftwidth=4
set showmatch
set background=dark
set encoding=utf8
set noswapfile
set laststatus=2
set foldmethod=indent
set foldlevel=99
set fileformat=unix
set splitbelow
set splitright
set nowrap

syntax on
filetype plugin indent on
colorscheme desert
autocmd BufWritePre * :%s/\s\+$//e

" plugin specific settings

" vim-latexsuite
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"
